// Generated by Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="LifeCardSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class UIImageView;
@class UILabel;
@class NSCoder;

SWIFT_CLASS("_TtC11LifeCardSDK24AddressItemTableViewCell")
@interface AddressItemTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageIconCheck;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelName;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIView;
@class NSLayoutConstraint;

SWIFT_CLASS("_TtC11LifeCardSDK27AddressServiceTableViewCell")
@interface AddressServiceTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewContent;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified widthViewOpen;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewOpen;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelName;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelAddress;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelTimeOpen;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelPhone;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelOpen;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (IBAction)didPressedGotoGoogleMap:(id _Nonnull)sender;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIWindow;
@class UIApplication;

SWIFT_CLASS("_TtC11LifeCardSDK11AppDelegate")
@interface AppDelegate : UIResponder <UIApplicationDelegate>
@property (nonatomic, strong) UIWindow * _Nullable window;
- (BOOL)application:(UIApplication * _Nonnull)application didFinishLaunchingWithOptions:(NSDictionary<UIApplicationLaunchOptionsKey, id> * _Nullable)launchOptions SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK9AreaModel")
@interface AreaModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11LifeCardSDK13BaseTableCell")
@interface BaseTableCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITableView;
@class UIScrollView;
@class NSBundle;

SWIFT_CLASS("_TtC11LifeCardSDK27BranchServiceViewController")
@interface BranchServiceViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelChoiceTinhTP;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelChoiceQuanHuyen;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelChoiceXaPhuong;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewTinhTP;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewQuanHuyen;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewXaPhuong;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewLostData;
- (void)viewDidLoad;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (IBAction)didChoiceTinhTP:(id _Nonnull)sender;
- (IBAction)didChoiceQuanHuyen:(id _Nonnull)sender;
- (IBAction)didChoiceXaPhuong:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@class UIButton;

SWIFT_CLASS("_TtC11LifeCardSDK26BuyCardFilterTableViewCell")
@interface BuyCardFilterTableViewCell : BaseTableCell
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewNewest;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewSavest;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lbSavest;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lbNewest;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewPrice;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lbPrice;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified btnPrice;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified btnSavest;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified btnNewest;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified iconPrice;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (IBAction)didNewest:(UIButton * _Nonnull)sender;
- (IBAction)didSavest:(UIButton * _Nonnull)sender;
- (IBAction)didPrice:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK21BuyCardViewController")
@interface BuyCardViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewHeader;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified heightViewHeader;
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
- (void)viewDidLoad;
- (void)refreshData;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end






@interface BuyCardViewController (SWIFT_EXTENSION(LifeCardSDK)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewWillEndDragging:(UIScrollView * _Nonnull)scrollView withVelocity:(CGPoint)velocity targetContentOffset:(CGPoint * _Nonnull)targetContentOffset;
@end


SWIFT_CLASS("_TtC11LifeCardSDK22CardCoverTableViewCell")
@interface CardCoverTableViewCell : BaseTableCell
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewShadow;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgCover;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgAvatar;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewDiscount;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewTextDiscount;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lbDiscountPrice;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewRadius;
- (void)awakeFromNib;
- (IBAction)didGoProvider:(UIButton * _Nonnull)sender;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK21CardInfoTableViewCell")
@interface CardInfoTableViewCell : BaseTableCell
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewShadow;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lbNameCard;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lbCode;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lbCurrentPrice;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lbOldPrice;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewRadius;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewMain;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified cstBottomMain;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK26CategoryCollectionViewCell")
@interface CategoryCollectionViewCell : UICollectionViewCell
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified icon;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lbName;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgArrow;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewBg;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK27ChoiceAddressViewController")
@interface ChoiceAddressViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITapGestureRecognizer;

SWIFT_CLASS("_TtC11LifeCardSDK44ContainerFloatingChoiceAddressViewController")
@interface ContainerFloatingChoiceAddressViewController : UIViewController
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)handleBackdropWithTapGesture:(UITapGestureRecognizer * _Nullable)tapGesture;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC11LifeCardSDK37ContainerFloatingQRCodeViewController")
@interface ContainerFloatingQRCodeViewController : UIViewController
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)handleBackdropWithTapGesture:(UITapGestureRecognizer * _Nullable)tapGesture;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC11LifeCardSDK38ContainerFloatingTermPayViewController")
@interface ContainerFloatingTermPayViewController : UIViewController
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)handleBackdropWithTapGesture:(UITapGestureRecognizer * _Nullable)tapGesture;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK32DefaultIconAndLabelTableViewCell")
@interface DefaultIconAndLabelTableViewCell : BaseTableCell
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified lbIcon;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lbText;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewMain;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewRadius;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified cstBottomMain;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewShadow;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified cstBottom;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK29DetailCardBottomTableViewCell")
@interface DetailCardBottomTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewContent;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK32DetailCardConditionTableViewCell")
@interface DetailCardConditionTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified cardNumberLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified conditionLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified codeLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified datePaidLabel;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified containerView;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK39DetailCardConditionWaitPayTableViewCell")
@interface DetailCardConditionWaitPayTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified codeLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified payLabel;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified containerView;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (IBAction)tutorialPayButtonClicked:(id _Nonnull)sender;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK28DetailCardCoverTableViewCell")
@interface DetailCardCoverTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified coverImageView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified codeLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified priceLabel1;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified priceLabel2;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified qrButton;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified discountView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified disCountLabel;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified disCountBg;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (IBAction)qrButtonClicked:(id _Nonnull)sender;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK40DetailCardInfomationServiceTableViewCell")
@interface DetailCardInfomationServiceTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified detailButton;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified priceLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified priceLabel1;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified priceLabel2;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified expiredDateLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified termLabel;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified iconImageView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified containerView;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (IBAction)detailButtonClicked:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK33DetailCardInfomationTableViewCell")
@interface DetailCardInfomationTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified view1;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified view2;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified view3;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel1;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel2;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified tileLabel3;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified valueLabel1;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified valueLabel2;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified valueLabel3;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified qrButton;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewContent;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (IBAction)qrButtonClicked:(id _Nonnull)sender;
- (IBAction)detailButtonClicked:(id _Nonnull)sender;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK32DetailCardPromotionTableViewCell")
@interface DetailCardPromotionTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewContent;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified tutorialLabel;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (IBAction)tutorialButtonClicked:(id _Nonnull)sender;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK27DetailCardRuleTableViewCell")
@interface DetailCardRuleTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelTitle;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified containerView;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK17DetailCardService")
@interface DetailCardService : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK26DetailCardTabTableViewCell")
@interface DetailCardTabTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified infoButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified ruleButton;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified containerView;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (IBAction)infoButtonClicked:(id _Nonnull)sender;
- (IBAction)ruleButtonClicked:(id _Nonnull)sender;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK24DetailCardViewController")
@interface DetailCardViewController : UIViewController
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified buyCardView;
- (void)viewDidLoad;
- (IBAction)backButtonClicked:(id _Nonnull)sender;
- (IBAction)buyCardButtonClicked:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


















@interface DetailCardViewController (SWIFT_EXTENSION(LifeCardSDK)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end

@class SwipeMenuView;

SWIFT_CLASS("_TtC11LifeCardSDK36DetailServiceContainerViewController")
@interface DetailServiceContainerViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified infoButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified historyButton;
@property (nonatomic, weak) IBOutlet SwipeMenuView * _Null_unspecified swipeView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
- (void)viewDidLoad;
- (IBAction)backButtonClicked:(id _Nonnull)sender;
- (IBAction)infoButtonClicked:(id _Nonnull)sender;
- (IBAction)historyButtonClicked:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end






SWIFT_CLASS("_TtC11LifeCardSDK33DetailServiceContentTableViewCell")
@interface DetailServiceContentTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified iconImageView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified priceLabel;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK30DetailServiceTextTableViewCell")
@interface DetailServiceTextTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified waitPayButton;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified cstWaitPayButton;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified lineView;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK27DetailServiceViewController")
@interface DetailServiceViewController : UIViewController
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified navigationView;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified cstHeightNavigation;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
- (void)viewDidLoad;
- (IBAction)backButtonClicked:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface DetailServiceViewController (SWIFT_EXTENSION(LifeCardSDK)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

@class UIColor;

SWIFT_CLASS("_TtC11LifeCardSDK12GradientView")
@interface GradientView : UIView
@property (nonatomic, strong) UIColor * _Nonnull startColor;
@property (nonatomic, strong) UIColor * _Nonnull endColor;
@property (nonatomic) double startLocation;
@property (nonatomic) double endLocation;
@property (nonatomic) BOOL horizontalMode;
@property (nonatomic) BOOL diagonalMode;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layerClass;)
+ (Class _Nonnull)layerClass SWIFT_WARN_UNUSED_RESULT;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK33HIstoryServiceResultTableViewCell")
@interface HIstoryServiceResultTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified dateView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified Value1View;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified Value2View;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified dateLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified value1Label;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified value2Label;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK10HandlePush")
@interface HandlePush : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK26HeaderPaymentTableViewCell")
@interface HeaderPaymentTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK32HistoeyServiceEmptyTableViewCell")
@interface HistoeyServiceEmptyTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK36HistoryServiceConditionTableViewCell")
@interface HistoryServiceConditionTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified conditionLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified dateLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified value1Label;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified value2Label;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITextField;

SWIFT_CLASS("_TtC11LifeCardSDK33HistoryServiceFilterTableViewCell")
@interface HistoryServiceFilterTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified transactionView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified dateView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified buttonView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified transactionButton;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified fromTextField;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified toTextField;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (IBAction)searchButtonClicked:(id _Nonnull)sender;
- (IBAction)transactionButtonClicked:(id _Nonnull)sender;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK40HistoryServiceSearchDetailViewController")
@interface HistoryServiceSearchDetailViewController : UIViewController
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified nameLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified priceLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified dateLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified value1Label;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified value2Label;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified value3Label;
- (void)viewDidLoad;
- (IBAction)backButtonClicked:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK38HistoryServiceTitleResultTableViewCell")
@interface HistoryServiceTitleResultTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified title1View;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified title2View;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified title3View;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified title2Label;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK28HistoryServiceViewController")
@interface HistoryServiceViewController : UIViewController
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
- (void)viewDidLoad;
- (void)toTextFieldDone;
- (void)cancelDatePicker;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end






@interface HistoryServiceViewController (SWIFT_EXTENSION(LifeCardSDK)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC11LifeCardSDK25HistoryTitleTableViewCell")
@interface HistoryTitleTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK24InfoPaymentTableViewCell")
@interface InfoPaymentTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified desLabel;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewContent;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK29IntroductSeviceViewController")
@interface IntroductSeviceViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
- (void)viewDidLoad;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK13LocationModel")
@interface LocationModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11LifeCardSDK24MyCardCoverTableViewCell")
@interface MyCardCoverTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewRadius;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewMain;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lbNameCard;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgCard;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewTypeCard;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified cstWidthViewTypeCard;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lbNumberCard;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewLine;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewShadow;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified cstBottomMain;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK23MyCardInfoTableViewCell")
@interface MyCardInfoTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lbAInfo;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lbAValue;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewLine;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lbBInfo;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lbBValue;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewRadius;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewMain;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewShadow;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified cstBottomMain;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK31MyCardOtherServiceTableViewCell")
@interface MyCardOtherServiceTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewRadius;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewMain;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lbOtherService;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified cstBottom;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified cstBottomMain;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewShadow;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK13MyCardService")
@interface MyCardService : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK26MyCardServiceTableViewCell")
@interface MyCardServiceTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewRadius;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewMain;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified icon;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lbValue;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lbNameService;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified cstBottom;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewShadow;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified cstBottomMain;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK20MyCardViewController")
@interface MyCardViewController : UIViewController
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewNavi;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified btnBuyCard;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewNoMyCard;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)refreshData;
- (IBAction)didShowBuyCard:(UIButton * _Nonnull)sender;
- (void)scrollViewWillEndDragging:(UIScrollView * _Nonnull)scrollView withVelocity:(CGPoint)velocity targetContentOffset:(CGPoint * _Nonnull)targetContentOffset;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface MyCardViewController (SWIFT_EXTENSION(LifeCardSDK)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC11LifeCardSDK32MyCodeCardItemCollectionViewCell")
@interface MyCodeCardItemCollectionViewCell : UICollectionViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelNameCard;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelCardNo;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageCard;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK36MyCodeInfomationServiceTableViewCell")
@interface MyCodeInfomationServiceTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewContent;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewIcon;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified valueLabel1;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified valueLabel2;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified valueLabel3;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified buttonAction;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageIconService;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewEffect;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelEffect;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified nameLabel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified detailButton;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (IBAction)detailButtonClicked:(UIButton * _Nonnull)sender;
- (IBAction)pressedShowQR:(id _Nonnull)sender;
- (IBAction)pressedGoToShopService:(id _Nonnull)sender;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK28MyCodeIntroductTableViewCell")
@interface MyCodeIntroductTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewContent;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelEmail;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelWebsite;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelFacebook;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelInfor;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (IBAction)pressedEmail:(id _Nonnull)sender;
- (IBAction)pressedWebsite:(id _Nonnull)sender;
- (IBAction)pressedFacebook:(id _Nonnull)sender;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UICollectionView;
@class UIPageControl;
@class UICollectionViewLayout;

SWIFT_CLASS("_TtC11LifeCardSDK27MyCodeListCardTableViewCell")
@interface MyCodeListCardTableViewCell : UITableViewCell <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelPage;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified heightViewCollectionView;
@property (nonatomic, weak) IBOutlet UICollectionView * _Null_unspecified collectionView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelNameCard;
@property (nonatomic, weak) IBOutlet UIPageControl * _Null_unspecified pageController;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewCollectionView;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK23MyCodeMyQRTableViewCell")
@interface MyCodeMyQRTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewQR;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageQR;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelPhone;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelName;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelTime;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (void)fireTimer;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK17MyCodeQRCodeModel")
@interface MyCodeQRCodeModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11LifeCardSDK24MyCodeTitleTableViewCell")
@interface MyCodeTitleTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewContent;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK20MyCodeViewController")
@interface MyCodeViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewBackGroudHeader;
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
- (void)viewDidLoad;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end














SWIFT_CLASS("_TtC11LifeCardSDK21NameCardTableViewCell")
@interface NameCardTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified desLabel;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified logoImage;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK34OtherPromoServiceCardTableViewCell")
@interface OtherPromoServiceCardTableViewCell : BaseTableCell
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewMain;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lbPromotion;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewRadius;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewShadow;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified cstBottomMain;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK19OwnAccountDtosModel")
@interface OwnAccountDtosModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11LifeCardSDK21PagedCollectionLayout")
@interface PagedCollectionLayout : UICollectionViewFlowLayout
- (CGPoint)targetContentOffsetForProposedContentOffset:(CGPoint)proposedContentOffset withScrollingVelocity:(CGPoint)velocity SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK12PaymentModel")
@interface PaymentModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11LifeCardSDK21PaymentViewController")
@interface PaymentViewController : UIViewController
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified table;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewCancel;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewPayment;
- (void)viewDidLoad;
- (IBAction)didSelectPayment:(id _Nonnull)sender;
- (IBAction)didSelectCancel:(id _Nonnull)sender;
- (IBAction)didSelectBack:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface PaymentViewController (SWIFT_EXTENSION(LifeCardSDK)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end

@class UIImage;

SWIFT_CLASS("_TtC11LifeCardSDK25PopupQRCodeViewController")
@interface PopupQRCodeViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewSaveAndShareImage;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelTime;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelName;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageQRCode;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelDescription;
- (void)viewDidLoad;
- (void)fireTimer;
- (IBAction)pressedSaveImage:(id _Nonnull)sender;
- (IBAction)pressedShareImage:(id _Nonnull)sender;
- (void)image:(UIImage * _Nonnull)image didFinishSavingWithError:(NSError * _Nullable)error contextInfo:(void const * _Nonnull)contextInfo;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK17ProvideInforModel")
@interface ProvideInforModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11LifeCardSDK20QRCodeViewController")
@interface QRCodeViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewPhoto;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewFlash;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewCamera;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (IBAction)didSelectFlash:(id _Nonnull)sender;
- (IBAction)didSelectPhoto:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImagePickerController;

@interface QRCodeViewController (SWIFT_EXTENSION(LifeCardSDK)) <UIImagePickerControllerDelegate, UINavigationControllerDelegate>
- (void)imagePickerController:(UIImagePickerController * _Nonnull)picker didFinishPickingMediaWithInfo:(NSDictionary<UIImagePickerControllerInfoKey, id> * _Nonnull)info;
- (void)imagePickerControllerDidCancel:(UIImagePickerController * _Nonnull)picker;
@end

@class AVCaptureMetadataOutput;
@class AVMetadataObject;
@class AVCaptureConnection;

@interface QRCodeViewController (SWIFT_EXTENSION(LifeCardSDK)) <AVCaptureMetadataOutputObjectsDelegate>
- (void)captureOutput:(AVCaptureMetadataOutput * _Nonnull)output didOutputMetadataObjects:(NSArray<AVMetadataObject *> * _Nonnull)metadataObjects fromConnection:(AVCaptureConnection * _Nonnull)connection;
@end


SWIFT_CLASS("_TtC11LifeCardSDK14RedisMetaModel")
@interface RedisMetaModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11LifeCardSDK26RoundedShadowTableViewCell")
@interface RoundedShadowTableViewCell : UITableViewCell
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)decoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier SWIFT_UNAVAILABLE;
@end

@class UIPanGestureRecognizer;

SWIFT_CLASS("_TtC11LifeCardSDK25ShopServiceViewController")
@interface ShopServiceViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewTop;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewHeader;
@property (nonatomic, weak) IBOutlet SwipeMenuView * _Null_unspecified swipMenu;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelPrepaidCard;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelBranch;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelIntroduce;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewAction;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified leftViewActive;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified heightViewTop;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified topViewTop;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelTitleHeader;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageCoverHeader;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageLogoHeader;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (IBAction)didPressedBack:(id _Nonnull)sender;
- (void)handlePanWithRecognizer:(UIPanGestureRecognizer * _Nonnull)recognizer;
- (IBAction)didPressedIntroduce:(id _Nonnull)sender;
- (IBAction)didPressedBranch:(id _Nonnull)sender;
- (IBAction)didPressedPrepaidCard:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end








SWIFT_CLASS("_TtC11LifeCardSDK13StyleDtoModel")
@interface StyleDtoModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11LifeCardSDK20TabbarViewController")
@interface TabbarViewController : UITabBarController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK20TermPayTableViewCell")
@interface TermPayTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified selectButton;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified selectView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified termButton;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (IBAction)didSelectChoose:(id _Nonnull)sender;
- (IBAction)didSelectTerm:(id _Nonnull)sender;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK21TermPayViewController")
@interface TermPayViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified viewRadius;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewLine;
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
- (void)viewDidLoad;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK33TermsAndConditionPayTableViewCell")
@interface TermsAndConditionPayTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified guildeLabel;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK22TitleCardTableViewCell")
@interface TitleCardTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITextView;

SWIFT_CLASS("_TtC11LifeCardSDK26TutorialGiftViewController")
@interface TutorialGiftViewController : UIViewController
@property (nonatomic, weak) IBOutlet UITextView * _Null_unspecified textView;
- (void)viewDidLoad;
- (IBAction)backButtonClicked:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK25TutorialPayViewController")
@interface TutorialPayViewController : UIViewController
@property (nonatomic, weak) IBOutlet UITextView * _Null_unspecified textView;
- (void)viewDidLoad;
- (IBAction)backButtonClicked:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end
































@interface UITextField (SWIFT_EXTENSION(LifeCardSDK))
@property (nonatomic) CGFloat paddingLeft;
@property (nonatomic, strong) UIColor * _Nonnull placeholderColor;
@end


@interface UITextView (SWIFT_EXTENSION(LifeCardSDK))
@property (nonatomic) CGFloat paddingLeft;
@end


@interface UIView (SWIFT_EXTENSION(LifeCardSDK))
@property (nonatomic, strong) UIColor * _Nonnull borderColor;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic) CGFloat cornerRadius;
@property (nonatomic) BOOL _radiusCircular;
@property (nonatomic, strong) UIColor * _Nonnull shadowColor;
@property (nonatomic) CGSize shadowOffset;
@property (nonatomic) CGFloat shadowOpacity;
@property (nonatomic) CGFloat shadowRadius;
@end






SWIFT_CLASS("_TtC11LifeCardSDK19ViewAlertNoInternet")
@interface ViewAlertNoInternet : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK19ViewCategoryBuyCard")
@interface ViewCategoryBuyCard : UIView
@property (nonatomic, weak) IBOutlet UICollectionView * _Null_unspecified collectionView;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ViewCategoryBuyCard (SWIFT_EXTENSION(LifeCardSDK)) <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC11LifeCardSDK18ViewTypeDetailCard")
@interface ViewTypeDetailCard : UIView
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewBackground;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified icon;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lbTitle;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LifeCardSDK11WSImageView")
@interface WSImageView : UIView
@property (nonatomic, strong) UIColor * _Null_unspecified tintColor;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@property (nonatomic) UIViewContentMode contentMode;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC11LifeCardSDK11WaitPayment")
@interface WaitPayment : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11LifeCardSDK25WaitPaymentViewController")
@interface WaitPaymentViewController : UIViewController
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified moneyLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified codeLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified dteLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified desLabel;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewPay;
- (void)viewDidLoad;
- (IBAction)didSelectPayment:(id _Nonnull)sender;
- (IBAction)didSelectBack:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
